import { layout } from '../components/layout'

export function AffirmationsPage(): string {
  return layout('Daily Affirmations', `

<!-- ── HERO ── -->
<section class="band-gold py-16 px-4 text-center relative overflow-hidden">
  <div class="peace-deco absolute top-4 left-8 text-7xl">✨</div>
  <div class="peace-deco absolute bottom-4 right-8 text-6xl">🌸</div>
  <div class="max-w-3xl mx-auto">
    <div class="tag-pill mb-4">✨ Daily Affirmations</div>
    <h1 class="font-display text-5xl md:text-6xl font-bold text-gray-800 mb-4">Funny. Honest. Healing.</h1>
    <p class="text-gray-600 text-xl max-w-xl mx-auto">
      Because sometimes you need a laugh AND a truth bomb at the same time. 😂💙
    </p>
  </div>
</section>

<!-- ── AFFIRMATION GENERATOR ── -->
<section class="py-20 px-4 bg-white">
  <div class="max-w-2xl mx-auto text-center">
    <div class="tag-pill mb-6">🎲 Affirmation Generator</div>
    <h2 class="font-display text-3xl font-bold text-gray-800 mb-8">Today's Affirmation</h2>

    <!-- Big card -->
    <div id="aff-card" class="peace-card p-10 mb-8 cursor-pointer relative" onclick="getNewAffirmation()" style="background: linear-gradient(135deg, #fef9e7, #f0f5ef);">
      <div class="absolute top-4 right-4 text-xs text-gray-400 font-bold uppercase tracking-widest">Click to refresh</div>
      <div id="aff-emoji" class="text-7xl mb-6">🌸</div>
      <p id="aff-text" class="font-display text-2xl md:text-3xl italic text-gray-800 leading-relaxed mb-6">
        "I am doing the best I can, and my best is more than enough."
      </p>
      <div id="aff-category" class="tag-pill">🌿 Self-Compassion</div>
    </div>

    <div class="flex flex-wrap gap-3 justify-center mb-8">
      <button onclick="getNewAffirmation()" class="btn-primary">
        ✨ New Affirmation
      </button>
      <button onclick="shareAffirmation()" class="btn-sage">
        📤 Share This
      </button>
      <button onclick="copyAffirmation()" class="btn-dusty">
        📋 Copy
      </button>
    </div>

    <!-- Category filter -->
    <div class="flex flex-wrap gap-2 justify-center">
      <span class="text-sm text-gray-500 self-center mr-2">Filter by:</span>
      <button onclick="filterAffirmations('all')" class="filter-btn active px-4 py-1.5 rounded-full text-sm font-bold border-2 border-clay-300 text-clay-500 hover:bg-clay-100 transition-colors" data-cat="all">All</button>
      <button onclick="filterAffirmations('recovery')" class="filter-btn px-4 py-1.5 rounded-full text-sm font-bold border-2 border-sage-300 text-sage-600 hover:bg-sage-100 transition-colors" data-cat="recovery">🌱 Recovery</button>
      <button onclick="filterAffirmations('funny')" class="filter-btn px-4 py-1.5 rounded-full text-sm font-bold border-2 border-gold-400 text-gold-600 hover:bg-gold-100 transition-colors" data-cat="funny">😂 Funny</button>
      <button onclick="filterAffirmations('anxiety')" class="filter-btn px-4 py-1.5 rounded-full text-sm font-bold border-2 border-dusty-300 text-dusty-500 hover:bg-dusty-100 transition-colors" data-cat="anxiety">🧠 Anxiety</button>
      <button onclick="filterAffirmations('self-love')" class="filter-btn px-4 py-1.5 rounded-full text-sm font-bold border-2 border-teal-300 text-teal-600 hover:bg-teal-100 transition-colors" data-cat="self-love">💙 Self-Love</button>
    </div>
  </div>
</section>

<!-- ── AFFIRMATION WALL ── -->
<section class="py-20 px-4 band-clay">
  <div class="max-w-6xl mx-auto">
    <div class="text-center mb-12">
      <div class="tag-pill mb-3">🧱 Affirmation Wall</div>
      <h2 class="font-display text-4xl font-bold text-gray-800 mb-3">All Affirmations</h2>
      <p class="text-gray-600">Save your favorites, share them, screenshot them. They're yours. 💙</p>
    </div>

    <div id="aff-grid" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
      <!-- Generated by JS -->
    </div>
  </div>
</section>

<!-- ── SUBMIT YOUR OWN ── -->
<section class="py-20 px-4 band-sage">
  <div class="max-w-2xl mx-auto text-center">
    <div class="tag-pill mb-4">📝 Community Affirmations</div>
    <h2 class="font-display text-3xl font-bold text-gray-800 mb-4">Write Your Own</h2>
    <p class="text-gray-600 mb-8">Have an affirmation that got you through? Share it with the community.</p>

    <div class="peace-card p-8 text-left">
      <div class="mb-5">
        <label class="block text-sm font-bold text-gray-700 mb-2">Your Affirmation ✍️</label>
        <textarea id="custom-aff" class="peace-input" rows="3" placeholder="e.g. I survived yesterday so I can try again today 💪"></textarea>
      </div>
      <div class="mb-5">
        <label class="block text-sm font-bold text-gray-700 mb-2">Category</label>
        <select id="custom-cat" class="peace-input">
          <option value="recovery">🌱 Recovery</option>
          <option value="funny">😂 Funny</option>
          <option value="anxiety">🧠 Anxiety</option>
          <option value="self-love">💙 Self-Love</option>
        </select>
      </div>
      <button onclick="submitAffirmation()" class="btn-primary w-full py-3">
        💙 Add to the Wall
      </button>
    </div>
  </div>
</section>

<!-- ── TIKTOK LINK ── -->
<section class="py-16 px-4 text-center" style="background: linear-gradient(135deg, #1a1a2e, #16213e);">
  <div class="max-w-xl mx-auto text-white">
    <p class="text-gray-400 mb-3 uppercase tracking-widest text-sm font-bold">Want more?</p>
    <h2 class="font-display text-3xl font-bold mb-4">New Affirmations Daily on TikTok</h2>
    <p class="text-gray-400 mb-6">Follow along for video affirmations that hit different. 🎬</p>
    <a href="https://www.tiktok.com/@findingpeace" target="_blank" class="tiktok-btn text-base px-8 py-3">
      <i class="fab fa-tiktok"></i> @FindingPeace on TikTok
    </a>
  </div>
</section>

<script>
const allAffirmations = [
  { text: "I am doing the best I can, and my best is more than enough.", emoji: "🌸", cat: "self-love" },
  { text: "Recovery isn't linear — and neither is my Wi-Fi, but here we are, still connected.", emoji: "😂", cat: "funny" },
  { text: "I chose myself today. That's the whole win.", emoji: "💪", cat: "self-love" },
  { text: "My healing doesn't have an expiration date.", emoji: "⏳", cat: "recovery" },
  { text: "Bad days don't cancel good futures.", emoji: "🌅", cat: "anxiety" },
  { text: "I am allowed to be a work in progress AND still love myself.", emoji: "🛠️", cat: "self-love" },
  { text: "I didn't survive this far to only survive this far.", emoji: "🔥", cat: "recovery" },
  { text: "Today I will be gentle with myself like I would be with someone I love.", emoji: "💙", cat: "self-love" },
  { text: "My story isn't over. The best plot twist is yet to come.", emoji: "📖", cat: "recovery" },
  { text: "Asking for help is a superpower, not a weakness.", emoji: "🦸", cat: "recovery" },
  { text: "I am worthy of peace. Full stop. No asterisks.", emoji: "☮️", cat: "self-love" },
  { text: "Some days just getting out of bed IS the victory. Crown, please. 👑", emoji: "😂", cat: "funny" },
  { text: "My anxiety lied to me again. Plot twist: I survived anyway.", emoji: "😤", cat: "anxiety" },
  { text: "I am not my worst day. I am every good choice I've ever made too.", emoji: "⚖️", cat: "recovery" },
  { text: "Sobriety looks good on me. So does pajamas. Both valid.", emoji: "😂", cat: "funny" },
  { text: "I release what I cannot control. Mostly. I'm working on it. 😅", emoji: "🎈", cat: "anxiety" },
  { text: "The version of me fighting to heal is the most courageous person I know.", emoji: "🦁", cat: "recovery" },
  { text: "I don't need to earn rest. I just need to rest.", emoji: "🌙", cat: "anxiety" },
  { text: "My brain is doing its best with limited data and a lot of old trauma. Valid.", emoji: "🧠", cat: "funny" },
  { text: "One day, one hour, one minute at a time. Today, I choose one more minute.", emoji: "⏱️", cat: "recovery" },
  { text: "I am healing even when it doesn't feel like it. Especially then.", emoji: "🌱", cat: "recovery" },
  { text: "The door I thought was locked was just stuck. I can push.", emoji: "🚪", cat: "anxiety" },
  { text: "I am allowed to change my mind, my path, and my whole life.", emoji: "🦋", cat: "self-love" },
  { text: "My past is a chapter, not the whole book.", emoji: "📚", cat: "self-love" },
];

const catNames = { all: 'All', recovery: '🌱 Recovery', funny: '😂 Funny', anxiety: '🧠 Anxiety', 'self-love': '💙 Self-Love' };
let currentFilter = 'all';
let currentIndex = 0;

function getFiltered() {
  return currentFilter === 'all' ? allAffirmations : allAffirmations.filter(a => a.cat === currentFilter);
}

function getNewAffirmation() {
  const filtered = getFiltered();
  let next = Math.floor(Math.random() * filtered.length);
  while (next === currentIndex && filtered.length > 1) next = Math.floor(Math.random() * filtered.length);
  currentIndex = next;
  const a = filtered[next];
  const card = document.getElementById('aff-card');
  card.style.opacity = '0';
  setTimeout(() => {
    document.getElementById('aff-emoji').textContent = a.emoji;
    document.getElementById('aff-text').textContent = '"' + a.text + '"';
    document.getElementById('aff-category').textContent = catNames[a.cat];
    card.style.opacity = '1';
    card.style.transition = 'opacity 0.4s';
  }, 300);
}

function filterAffirmations(cat) {
  currentFilter = cat;
  document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active', 'bg-clay-100'));
  document.querySelector('[data-cat="' + cat + '"]').classList.add('active', 'bg-clay-100');
  getNewAffirmation();
  renderGrid();
}

function shareAffirmation() {
  const text = document.getElementById('aff-text').textContent;
  if (navigator.share) {
    navigator.share({ text: text + ' — Finding Peace' });
  } else {
    copyAffirmation();
    showToast('✨ Affirmation copied! Ready to share.');
  }
}

function copyAffirmation() {
  const text = document.getElementById('aff-text').textContent + ' — Finding Peace';
  navigator.clipboard.writeText(text).then(() => showToast('📋 Copied to clipboard!'));
}

function submitAffirmation() {
  const text = document.getElementById('custom-aff').value.trim();
  const cat = document.getElementById('custom-cat').value;
  if (!text) { showToast('Please write your affirmation first 💙'); return; }
  const emojis = { recovery:'🌱', funny:'😂', anxiety:'🧠', 'self-love':'💙' };
  allAffirmations.unshift({ text, emoji: emojis[cat], cat });
  document.getElementById('custom-aff').value = '';
  renderGrid();
  showToast('🌸 Your affirmation was added to the wall! Thank you!');
}

function renderGrid() {
  const grid = document.getElementById('aff-grid');
  const filtered = getFiltered();
  const colors = [
    { bg: '#fef9e7', border: '#f5c430' },
    { bg: '#f0f5ef', border: '#8ab88e' },
    { bg: '#f3eef8', border: '#a07fc8' },
    { bg: '#e8f7f5', border: '#4fbdb3' },
    { bg: '#fdf3ec', border: '#e8924d' },
  ];
  grid.innerHTML = filtered.map((a, i) => {
    const c = colors[i % colors.length];
    return \`<div class="peace-card p-6 cursor-pointer" style="background:\${c.bg}; border-left: 4px solid \${c.border};" onclick="setAffirmation(\${allAffirmations.indexOf(a)})">
      <div class="text-3xl mb-3">\${a.emoji}</div>
      <p class="font-display italic text-gray-700 text-base leading-relaxed mb-3">"\${a.text}"</p>
      <div class="flex items-center justify-between">
        <span class="tag-pill text-xs">\${catNames[a.cat]}</span>
        <button class="text-gray-400 hover:text-clay-500 text-sm transition-colors" onclick="event.stopPropagation();copyFromGrid('\${a.text.replace(/'/g, "\\\\'")}')" title="Copy">
          <i class="fas fa-copy"></i>
        </button>
      </div>
    </div>\`;
  }).join('');
}

function setAffirmation(idx) {
  currentIndex = idx;
  const a = allAffirmations[idx];
  document.getElementById('aff-emoji').textContent = a.emoji;
  document.getElementById('aff-text').textContent = '"' + a.text + '"';
  document.getElementById('aff-category').textContent = catNames[a.cat];
  window.scrollTo({ top: 0, behavior: 'smooth' });
}

function copyFromGrid(text) {
  navigator.clipboard.writeText('"' + text + '" — Finding Peace').then(() => showToast('📋 Copied!'));
}

// Init
renderGrid();
</script>
`, '/affirmations')
}
